#!/bin/bash
S2E_ROOT=/home/vadim/s2es/s2e-04-12
S2E_QEMU_ROOT=$S2E_ROOT/build/qemu-release/
QEMU_NAME=qemu-system-i386
VM_IMAGE=../s2e_mini.qcow2
VM_SNAPSHOT=ready2
VM_MEMORY=250
#DEFAULT_FLAGS="-net nic,model=pcnet -redir tcp:2222::22 -net user"

FLAGS=${*:--loadvm $VM_SNAPSHOT}
if [[ "$0" =~ .*crun ]]; then
	S2E_QEMU_VERSION=i386-softmmu
else
	S2E_QEMU_VERSION=i386-s2e-softmmu
	S2E_ARGS="-s2e-config-file conf.lua -s2e-verbose"
fi


QEMU_BIN=$S2E_QEMU_ROOT/$S2E_QEMU_VERSION/$QEMU_NAME

$QEMU_BIN -m $VM_MEMORY -hda $VM_IMAGE $S2E_ARGS $DEFAULT_FLAGS $FLAGS
